import { red } from "@material-ui/core/colors";
import {
    Add,
    AssignmentTurnedIn,
    CloudUpload,
    DirectionsRun,
    Home,
    LibraryAddCheck,
    LocalPharmacy,
    PermDataSetting,
    Launch,
    SpeakerNotes,
    Dashboard,
    Help,
    Folder,
    AccountCircle,
    Business,
    RecentActors,
    Store,
    Email,
    AlternateEmail,
    Security,
    Map,
    PeopleAlt,
    VpnKey,
    AssignmentInd,
    AccountTree,
    GroupWork,
    Polymer,
    PostAdd,
    NoteAdd,
    Ballot,
    BallotOutlined,
    ContactMail,
    ColorLens,
    Brightness6Outlined,
    Description,
    Person,
    Storage,
    ThumbUp,
    ThumbDown,
    Receipt,
    ViewCarousel,
    TrendingUp,
    Menu,
    Search,
    Lens,
    AddCircleOutline,
    ViewList,
    Refresh,
    EventNote,
    Event,
    Alarm,
    Chat,
    Assignment,
    Build,
    Close,
    Done,
    ArrowBack,
    Feedback,
    Widgets,
    Delete,
    Edit,
    CheckCircleOutlineOutlined,
    EditOutlined,
    Remove,
    Save,
    ExpandLess,
    ExpandMore,
    DeleteOutline,
    DeleteForever,
    Translate,
    AttachMoney,
    Settings,
    PowerSettingsNew,
    WbIncandescent,
    WbIncandescentOutlined,
    WbIncandescentTwoTone,
    EmojiObjects,
    Flare,
    Highlight,
    ZoomIn,
    SwapCalls,
    Link,
    LinkOff,
    MoreVert,
    MoreHoriz,
    SpeakerNotesOff,
    NotListedLocation,
    GetApp,
    People,
    ViewColumnTwoTone,
    ViewWeek,
    CalendarViewDaySharp,
    FormatListBulletedSharp,
    ArrowBackIos,
    ArrowForwardIos,
    Clear,
    NotificationImportantRounded,
    NotificationsActive,
    Notifications
} from "@material-ui/icons";

const MatIconService = {
    MENU: <Menu />,
    BACK: <ArrowBack />,
    SAVE: <Save />,
    CLEAR: <Clear />,
    RELOAD: <Refresh />,
    CONTRAST: <Brightness6Outlined />,
    SEARCH: <Search />,
    ACCOUNT: <AccountCircle />,
    SETTINGS: <Settings />,
    HOME: <Home />,
    NOTIFICATIONS: <Notifications />,
    LOGOUT: <PowerSettingsNew style={{ color: red[500] }} />,
}
export default MatIconService;